//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ninja.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://developer.microsoft.com/en-us/microsoft-edge/webview2/.
        /// </summary>
        public static string MicrosoftEdgeWebView2Runtime_DownloadUrl {
            get {
                return ResourceManager.GetString("MicrosoftEdgeWebView2Runtime_DownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/is-leeroy-jenkins/Ninja/blob/main/Contributors.md.
        /// </summary>
        public static string Ninja_Contributors {
            get {
                return ResourceManager.GetString("Ninja_Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        public static string Ninja_GitHub_Repo {
            get {
                return ResourceManager.GetString("Ninja_GitHub_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BornToBeRoot.
        /// </summary>
        public static string Ninja_GitHub_User {
            get {
                return ResourceManager.GetString("Ninja_GitHub_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://borntoberoot.net/Ninja/Download.
        /// </summary>
        public static string Ninja_LatestReleaseUrl {
            get {
                return ResourceManager.GetString("Ninja_LatestReleaseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GNU General Public License v3.0.
        /// </summary>
        public static string Ninja_License {
            get {
                return ResourceManager.GetString("Ninja_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/is-leeroy-jenkins/Ninja/blob/main/LICENSE.
        /// </summary>
        public static string Ninja_LicenseUrl {
            get {
                return ResourceManager.GetString("Ninja_LicenseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/is-leeroy-jenkins/Ninja/issues/new/choose.
        /// </summary>
        public static string Ninja_NewIssueUrl {
            get {
                return ResourceManager.GetString("Ninja_NewIssueUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninja.
        /// </summary>
        public static string Ninja_ProjectName {
            get {
                return ResourceManager.GetString("Ninja_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/is-leeroy-jenkins/Ninja.
        /// </summary>
        public static string Ninja_ProjectUrl {
            get {
                return ResourceManager.GetString("Ninja_ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/is-leeroy-jenkins/Ninja.
        /// </summary>
        public static string Ninja_RepoUrl {
            get {
                return ResourceManager.GetString("Ninja_RepoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.transifex.com/is-leeroy-jenkins/Ninja/.
        /// </summary>
        public static string Ninja_TranslationUrl {
            get {
                return ResourceManager.GetString("Ninja_TranslationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/_BornToBeRoot.
        /// </summary>
        public static string Ninja_TwitterUrl {
            get {
                return ResourceManager.GetString("Ninja_TwitterUrl", resourceCulture);
            }
        }
    }
}
